local map = vim.keymap.set

map("n", "<leader>rr", vim.lsp.buf.rename)
map("n", "<leader>qq", vim.cmd.Ex)
map("n", "<leader>qb", ":bd<CR>")
map("n", "<leader>tn", ":terminal<CR>:startinsert<CR>")
map("t", "<C-x>", "exit<CR>")
map("t", "<C-l>", "<C-\\><C-n>:b#<CR>")
map("t", "<C-n>", "<C-\\><C-n>")
map("t", "<C-t>", "<C-\\><C-o>:terminal<CR>")

map("n", "<leader>ws", "<C-w><C-s>")
map("n", "<leader>wv", "<C-w><C-v>")
map("n", "<leader>wq", "<C-w><C-q>")
map("n", "<leader>wk", "<C-w><C-k>")
map("n", "<leader>wl", "<C-w><C-l>")
map("n", "<leader>wj", "<C-w><C-j>")
map("n", "<leader>wh", "<C-w><C-h>")


map("v", "<", "<gv")
map("v", ">", ">gv")
map("n", ">", ">>")
map("n", "<", "<<")
map("v", "p", "_dp")
map("n", "<C-n>", ":nohlsearch<Bar>:echo<CR>")
map("n", "<leader>k", vim.lsp.buf.hover, { noremap = true, silent = true })
map("n", "<leader>d", vim.diagnostic.open_float)
map("n", "J", "m`o<Esc>``")
map("n", "K", "m`O<Esc>``", { noremap = true, silent = true })
map("v", "J", ":m '>+1<CR>gv=gv")
map("v", "K", ":m '<-2<CR>gv=gv")
