return {
	"tpope/vim-fugitive",
	config = function()
		vim.keymap.set("n", "<leader>gg", vim.cmd.Git)
		vim.keymap.set("n", "<leader>gD", vim.cmd.Gdiffsplit)
		vim.keymap.set("n", "<leader>gC", function()
			local branch = vim.fn.input("Branch name: ")
			if branch ~= "" then
				vim.cmd.Git("checkout -b " .. branch)
				vim.cmd.Git("push -u origin " .. branch)
			end
		end)
		vim.keymap.set("n", "<leader>gA", function()
			vim.cmd.Git("add --all")
		end)
		vim.keymap.set("n", "<leader>ga", function()
			vim.cmd.Git("add " .. vim.fn.expand("%"))
		end)
		vim.keymap.set("n", "<leader>gc", function()
			vim.cmd.Git("commit")
		end)
		vim.keymap.set("n", "<leader>gp", function()
			vim.cmd.Git("push")
		end)
		vim.keymap.set("n", "<leader>gP", function()
			local default = vim.cmd.Git("symbolic-ref refs/remotes/origin/HEAD --short")
			vim.cmd.Git("pull --rebase " .. default)
		end)
		vim.keymap.set("n", "<leader>gB", function()
			vim.cmd.Git("blame")
		end)
		vim.keymap.set("n", "<leader>gm", function()
			vim.cmd.Git("mergetool")
		end)
		vim.keymap.set("n", "<leader>gd", function()
			vim.cmd.Git("diff")
		end)
		vim.keymap.set("n", "<leader>gl", function()
			vim.cmd.Git("log")
		end)
		vim.keymap.set("n", "<leader>gu", function()
			vim.cmd.Git("restore --staged " .. vim.fn.expand("%"))
		end)
		vim.keymap.set("n", "<leader>gU", function()
			vim.cmd.Git("restore --staged :/")
		end)
		vim.keymap.set("n", "<leader>gsp", function()
			local message = vim.fn.input("Stash message: ")
			local file = vim.fn.expand("%")
			vim.cmd.Git("stash push --message '" .. message .. "' " .. file)
		end)
		vim.keymap.set("n", "<leader>gsl", function()
			vim.cmd.Git("stash list")
		end)
		vim.keymap.set("n", "<leader>gsP", function()
			local stash = vim.fn.input("Stash name: ")
			vim.cmd.Git("stash pop " .. stash)
		end)
		vim.keymap.set("n", "<leader>gsc", function()
			vim.cmd.Git("stash clear")
		end)
		vim.keymap.set("n", "<leader>gr", function()
			local file = vim.fn.expand("%")
			local confirm = vim.fn.input("Do you want to restore this file(yes/no): ")
			if confirm == "yes" then
				vim.cmd.Git("restore " .. file)
			end
		end)
		vim.keymap.set("n", "<leader>gR", function()
			local confirm = vim.fn.input("Do you want to restore ALL files (yes/no): ")
			if confirm == "yes" then
				vim.cmd.Git("restore .")
			end
		end)

		vim.opt.diffopt:append("algorithm:patience")
		vim.opt.diffopt:append("indent-heuristic")

		vim.keymap.set("n", "<leader>gj", ":diffget //3<CR>")
		vim.keymap.set("n", "<leader>gf", ":diffget //2<CR>")
		vim.keymap.set("n", "<leader>go", function()
			local conflict_pattern = "^<<<<<<< "
			local conflicts = vim.fn.search(conflict_pattern, "n")
			print("Remaining conflicts: " .. conflicts)
		end)
	end,
}
